"""Add User model for Google OAuth

Revision ID: 02732c845b08
Revises: 6a1efe7c6dd8
Create Date: 2025-05-10 17:41:22.651418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02732c845b08'
down_revision = '6a1efe7c6dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.drop_index('idx_gin_hairstyle_name_trgm', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.create_index('idx_gin_hairstyle_name_trgm', ['name'], unique=False, postgresql_using='gin')

    op.drop_table('user')
    # ### end Alembic commands ###
