"""Add brand_price and normal_price to Hairstyle table

Revision ID: 6a1efe7c6dd8
Revises: dcdee634e623
Create Date: 2025-04-16 17:40:58.944525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1efe7c6dd8'
down_revision = 'dcdee634e623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('normal_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.drop_column('normal_price')
        batch_op.drop_column('brand_price')

    # ### end Alembic commands ###
