"""Create Hairstyle table

Revision ID: 6b4d19c7e3eb
Revises: 
Create Date: 2025-04-10 20:48:58.566318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4d19c7e3eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hairstyle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hairstyle_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hairstyle_name'))

    op.drop_table('hairstyle')
    # ### end Alembic commands ###
