"""Remove similar_styles relationship from Hairstyle

Revision ID: b1d0551573cd
Revises: d144dc0a34d2
Create Date: 2025-04-10 22:25:34.466283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d0551573cd'
down_revision = 'd144dc0a34d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hairstyle_similarities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hairstyle_similarities',
    sa.Column('hairstyle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('similar_style_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hairstyle_id'], ['hairstyle.id'], name='hairstyle_similarities_hairstyle_id_fkey'),
    sa.ForeignKeyConstraint(['similar_style_id'], ['hairstyle.id'], name='hairstyle_similarities_similar_style_id_fkey'),
    sa.PrimaryKeyConstraint('hairstyle_id', 'similar_style_id', name='hairstyle_similarities_pkey')
    )
    # ### end Alembic commands ###
