"""Add similar_styles relationship to Hairstyle

Revision ID: d144dc0a34d2
Revises: 6b4d19c7e3eb
Create Date: 2025-04-10 22:17:47.449682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd144dc0a34d2'
down_revision = '6b4d19c7e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hairstyle_similarities',
    sa.Column('hairstyle_id', sa.Integer(), nullable=False),
    sa.Column('similar_style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hairstyle_id'], ['hairstyle.id'], ),
    sa.ForeignKeyConstraint(['similar_style_id'], ['hairstyle.id'], ),
    sa.PrimaryKeyConstraint('hairstyle_id', 'similar_style_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hairstyle_similarities')
    # ### end Alembic commands ###
