"""Add similar_styles_description to Hairstyle

Revision ID: dcdee634e623
Revises: b1d0551573cd
Create Date: 2025-04-10 22:39:14.637853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdee634e623'
down_revision = 'b1d0551573cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_styles_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyle', schema=None) as batch_op:
        batch_op.drop_column('similar_styles_description')

    # ### end Alembic commands ###
